### ISSUE TITLE
.objectId replaced by .id

### ISSUE THREAD

**Issue by biy1** [PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers#10]
It seems that [].objectId got replaced by [].id. This makes most of the scripts fail, as the parameter (e.g. $userid) will be null, because objectId does not exist as attribute. I can fix it by modifying each script before running, but think it would be helpful for others to fix the issues directly in the repo.

**Comment by rajat-packt** [comment]
We have contacted the author, all the required changes will be made post their verification.

**Comment by kfosaaen** [comment]
This was just addressed with the latest PR merge.
