### ISSUE TITLE
Solution for Prevention

### ISSUE THREAD

**Issue by cheahengsoon** [PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers#2]
Hi @davidokeyode ,
Any solution for prevent the demo in Microsoft Defender for cloud?
For Example, Prevent Azure Password Spray

**Comment by davidokeyode** [comment]
@cheahengsoon Sorry I missed this. Yeah detection exists in MDC. There are ways that an attacker could look to work around by doing things like varying the source IP and implementing backoff techniques.
