### ISSUE TITLE
Your deployment failed Deployment name:TemplateDeployment

### ISSUE THREAD

**Issue by Felipetsa** [PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers#3]
Hi,
When I run > Invoke-WebRequest http://bit.ly/reader-scenarios -O reader-scenario.ps1 (Page 187) I'm getting "Deployment failed. Click here for details"

Error details:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message":"Website with given name webap-n77iodknbqbau already exists."}]}

Status: Conflict

{
    "status": "Failed",
    "error": {
        "code": "Conflict",
        "message": "Website with given name webap-n77iodknbqbau already exists.",
        "details": [
            {
                "message": "Website with given name webap-n77iodknbqbau already exists."
            },
            {
                "code": "Conflict"
            },
            {}
        ]
    }
}
![chrome_aC4od6boMu](https://user-images.githubusercontent.com/69634381/154674159-90390ce4-741a-48de-a44c-3e63888fd283.png)

**Comment by davidokeyode** [comment]
Hi Felipe, can you try running it again? Seems like the random name generated for the app already existed. Delete the resource group and rerun. Let me know how it goes.

**Comment by Felipetsa** [comment]
Hi David, many thanks for your reply! I've deleted "Pentest-rg" resource group and I rerun the script, but the problem is still the same.
<img width="396" alt="chrome_rCyiw5OM07" src="https://user-images.githubusercontent.com/69634381/155121774-05886b8a-e275-4fbf-ad6c-cbcd6a0f1d42.png">
<img width="1919" alt="jfs3ND53kJ" src="https://user-images.githubusercontent.com/69634381/155128292-e6f5b313-e0ee-43a7-8818-6c776fdc2cef.png">

I'm also attaching the deployment result:
[reader-account-output.txt](https://github.com/PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers/files/8116200/reader-account-output.txt)

I have 4 resource groups in my tenant at the moment:
<img width="959" alt="chrome_Lrr2Nztq1h" src="https://user-images.githubusercontent.com/69634381/155123446-17a61b49-f122-443e-9ff3-8ebf4065f28a.png">

Does it matter which country I'm in? I'm in the North Europe region.

Thank you your assistance!




.

**Comment by Felipetsa** [comment]
Hi David, sorry for the hassle but do you have any clue? Just impacting my way through the book. Thank you.

**Comment by swattor** [comment]
It seems that the script does not create a random name. I have the same failure with the same message failed to create 'webap-n77iodknbqbau' 

It looks like a bug - all the other resources are created with uniqueString(resourceGroup().id))]" whereas the webapp is created with uniqueString(resourceGroup().name))]"

**Comment by Felipetsa** [comment]
Hi @swattor , I got it sorted following the steps below:

1. Delete the resource group.
2. Copy the script https://raw.githubusercontent.com/PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers/main/chapter-4/resources/badtemplate.json and edit it using your favorite editor.
3. Search for this line on the script: **"defaultValue": "[concat('webap-'** and change it to **"defaultValue": "[concat('webapp-'**
4. Upload the script here on GitHub keeping the same name badtemplate.json
5. Edit reader-scenario.ps1 and point it to your new badtemplate.json path (https://raw.githubusercontent.com/YOUR-GITHUB/reader-scenario.ps1
6. Run it again.

Unfortunately, I had little support from the authors on this problem. Hope this works for you too.

**Comment by kfosaaen** [comment]
I've corrected the "webap" line in the template file. Sorry for the delays in addressing this. My notifications got turned off for issues on the repo. I've tested this in my own environment and it appears to be running correctly now.
