### ISSUE TITLE
Page 140 - Deployments Password  

### ISSUE THREAD

**Issue by S1nEat3r** [PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers#6]
I have noticed that when reviewing the deployments output the vm admin password is now set as "SecureString" and not in plaintext. I am assuming that Microsoft have gotten wise to this?

**Comment by kfosaaen** [comment]
Corrected on this commit - https://github.com/PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers/commit/f77bb6a10136ea651a1e0d88130a27669fb62b70
