### ISSUE TITLE
Deployment Template VM Size is not available in most regions

### ISSUE THREAD

**Issue by micmaher** [PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers#7]
Tried deploying to North Europe, US East, West Europe but VM wasn't available. 

Got UK South to work (which is the region the book used)

![image](https://user-images.githubusercontent.com/17732001/170581570-32f45983-f8c8-447f-958f-f1acbce1e67d.png)

**Comment by jeffbencteux** [comment]
Got the same. Workaround for me was to deploy the pentest VM to japan and the exercises to eastasia. Do not forget to edit the exercises scripts before running them if you do that (`location = "eastasia"`).

**Comment by kfosaaen** [comment]
Is this still an issue? I just checked in my own subscription in the central US region and the VM size was available.
![image](https://user-images.githubusercontent.com/2163397/179373549-461a472d-1a8f-4aaa-9966-f32c9aa77074.png)

**Comment by micmaher** [comment]
No its no longer an issue for me given I used Japan.
