### ISSUE TITLE
Ubuntu Installation Failure

### ISSUE THREAD

**Issue by dievus** [PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers#9]
Hi there. Just going through installation and getting errors that the version of Ubuntu installed is invalid.

I added wsl-ubuntu-2004 to the permalink below in my local installation, which worked. Just to avoid any issues, and to make the process easier, I would ask/recommend adding Ubuntu to the choco install line as part of the installation script. 

https://github.com/PacktPublishing/Penetration-Testing-Azure-for-Ethical-Hackers/blob/4aa54236b12aaf3f41b8a005b1f276160265d3fe/chapter-2/pentest-vm-template/installscript.ps1#L12

**Comment by rajat-packt** [comment]
Thanks for the suggestion!
